package edu.pitt.lab5;

import java.util.Random;
import javax.swing.JOptionPane;

public class Dice {
	public static void rollDice(int times, Random random) {
		int numTwo = 0, numThree = 0, numFour = 0, numFive = 0, numSix = 0, numSeven = 0, numEight = 0,
				numNine = 0, numTen = 0, numEleven = 0, numTwelve = 0;
		
		int firstRoll, secondRoll;
		
		for (int i = 0; i < times; i++) {
			firstRoll = random.nextInt(6) + 1;
			secondRoll = random.nextInt(6) + 1;
			
			switch (firstRoll + secondRoll) {
			case 2 : numTwo++; break;
			case 3 : numThree++; break;
			case 4 : numFour++; break;
			case 5 : numFive++; break;
			case 6 : numSix++; break;
			case 7 : numSeven++; break;
			case 8 : numEight++; break;
			case 9 : numNine++; break;
			case 10 : numTen++; break;
			case 11 : numEleven++; break;
			case 12 : numTwelve++; break;
			}
		}
		System.out.println("Results generated by rolling the dice " + times + " times: ");
		System.out.println("Value\tTimes\tFraction");
		System.out.println("2\t" + numTwo + "\t" + numTwo + "/" + times);
		System.out.println("3\t" + numThree + "\t" + numThree + "/" + times);
		System.out.println("4\t" + numFour + "\t" + numFour + "/" + times);
		System.out.println("5\t" + numFive + "\t" + numFive + "/" + times);
		System.out.println("6\t" + numSix + "\t" + numSix + "/" + times);
		System.out.println("7\t" + numSeven + "\t" + numSeven + "/" + times);
		System.out.println("8\t" + numEight + "\t" + numEight + "/" + times);
		System.out.println("9\t" + numNine + "\t" + numNine + "/" + times);
		System.out.println("10\t" + numTen + "\t" + numTen + "/" + times);
		System.out.println("11\t" + numEleven + "\t" + numEleven + "/" + times);
		System.out.println("12\t" + numTwelve + "\t" + numTwelve + "/" + times);
		System.out.println("====================");

	}
	
	public static void main(String[] args) {
		Random random = new Random();
		int times;
		String response;
		
		do {
			times = Integer.parseInt(JOptionPane.showInputDialog("Please enter the times you want to roll the dice: "));
			
			rollDice(times, random);
			
			do {
				response = JOptionPane.showInputDialog("Do you want to repeat the process? (Y/N)");
				
				if ("N".equalsIgnoreCase(response)) System.exit(0);
			} while (!"Y".equalsIgnoreCase(response));
			
		} while (true);
	}

}
